### ISSUE TITLE
[client] tabs drag and drop doesn't work on chrome

### ISSUE THREAD

**Issue by CodeMyst** [pastemyst/pastemyst-v3#32]

**Comment by CodeMyst** [comment]
On chrome it breaks because of hiding the ghost of the moved tab in SortableJS.

```scss
.tabs .tabgroup :global(.sortable-drag) {
    display: none;
}
```
